# Generated by Django 2.2.5 on 2019-09-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=5)),
                ('chestpain', models.CharField(choices=[('Typical Angina', 'Typical Angina'), ('Atypical Angina', 'Atypical Angina'), ('Non-anginal Pain', 'Non-anginal Pain'), ('Asymptomatic', 'Asymptomatic')], max_length=5)),
                ('blood_pressure', models.IntegerField(default=0)),
                ('cholestrol', models.IntegerField(default=0)),
                ('sugar', models.CharField(choices=[('Less than 120mg/dl', 'Less than 120mg/dl'), ('More than 120mg/dl', 'More than 120mg/dl')], max_length=5)),
                ('restecg', models.CharField(choices=[('Normal', 'Normal'), ('ST-T wave abnormality', 'ST-T wave abnormality'), (' Estes criteria', 'Estes criteria')], max_length=5)),
                ('max_heart_rate', models.IntegerField(default=0)),
                ('exang', models.IntegerField(default=0)),
                ('oldpeak', models.IntegerField(default=0)),
            ],
        ),
    ]
