# Generated by Django 2.2.5 on 2019-09-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartapi', '0002_auto_20190929_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='chestpain',
            field=models.CharField(choices=[('Typical Angina', 'Typical Angina'), ('Atypical Angina', 'Atypical Angina'), ('Non-anginal Pain', 'Non-anginal Pain'), ('Asymptomatic', 'Asymptomatic')], max_length=30),
        ),
        migrations.AlterField(
            model_name='test',
            name='restecg',
            field=models.CharField(choices=[('Normal', 'Normal'), ('ST-T wave abnormality', 'ST-T wave abnormality'), (' Estes criteria', 'Estes criteria')], max_length=30),
        ),
        migrations.AlterField(
            model_name='test',
            name='sugar',
            field=models.CharField(choices=[('Less than 120mg/dl', 'Less than 120mg/dl'), ('More than 120mg/dl', 'More than 120mg/dl')], max_length=30),
        ),
    ]
