# Generated by Django 2.2.5 on 2019-09-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartapi', '0003_auto_20190929_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='sex',
            field=models.CharField(choices=[('1', 'Male'), ('0', 'Female')], max_length=5),
        ),
    ]
