# Generated by Django 2.2.5 on 2019-09-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartapi', '0004_auto_20190929_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='chestpain',
            field=models.CharField(choices=[('1', 'Typical Angina'), ('2', 'Atypical Angina'), ('3', 'Non-anginal Pain'), ('4', 'Asymptomatic')], max_length=30),
        ),
        migrations.AlterField(
            model_name='test',
            name='restecg',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'ST-T wave abnormality'), ('2', 'Estes criteria')], max_length=30),
        ),
        migrations.AlterField(
            model_name='test',
            name='sugar',
            field=models.CharField(choices=[('0', 'Less than 120mg/dl'), ('1', 'More than 120mg/dl')], max_length=30),
        ),
    ]
